name: Build and publish

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
    - name: No Operation Step
      run: echo "This is a noop step. No operations performed."
